spring:
  datasource:
    username: root
    password: admin
    url: jdbc:mysql://localhost:3306/demo?characterEncoding=utf8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    open-in-view: true
    generate-ddl: true
    show-sql: true
    properties:
      hibernate.format_sql: true
      org:
        hibernate:
          envers:
            audit_table_suffix: _AUDIT
            revision_field_name: REVISION_ID
            revision_type_field_name: REVISION_TYPE
#      hibernate.connection.autocommit: true
#      hibernate.globally_quoted_identifiers: true  #创建表结构报错via JDBC Statement
  main:
    allow-bean-definition-overriding: true
#mybatis:
#  mapper-locations: classpath:mapper/*.xml
logging:
  level:
    com.qp: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace
    org.hibernate.type.descriptor.sql.BasicExtractor: trace

blog:
  title: Blog
  banner:
    title: Warning
    content: The blog will be down tomorrow.


