/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    java
    kotlin("jvm")
    `java-library`
    kotlin("plugin.spring")
    kotlin("plugin.jpa")
    kotlin("kapt")
}

dependencies {
    //引入依赖版本统一管理模块
//    implementation(platform(project(":qp-bom")))
    implementation("cn.hutool:hutool-all")
    implementation(kotlin("stdlib"))
    implementation(kotlin("reflect"))
    implementation("io.hypersistence:hypersistence-utils-hibernate-60")
    implementation("org.hibernate.orm:hibernate-envers")
    implementation("org.springframework.boot:spring-boot-starter-web")
    implementation("org.springframework.boot:spring-boot-starter-data-jpa")
    compileOnly("org.projectlombok:lombok:+")
    annotationProcessor("org.projectlombok:lombok:+")
//    annotationProcessor("org.springframework.boot:spring-boot-configuration-processor")
    runtimeOnly("com.mysql:mysql-connector-j")
    testImplementation("org.springframework.boot:spring-boot-starter-test")
    testImplementation("com.ninja-squad:springmockk")
    testCompileOnly("org.projectlombok:lombok:+")
    testAnnotationProcessor("org.projectlombok:lombok:+")
}
configurations {
    compileOnly {
        extendsFrom(configurations.annotationProcessor.get())
    }
}
allOpen {
    annotation("jakarta.persistence.Entity")
    annotation("jakarta.persistence.Embeddable")
    annotation("jakarta.persistence.MappedSuperclass")
}
noArg {
    annotation("jakarta.persistence.Entity")
}