/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.qp;

import lombok.extern.slf4j.Slf4j;

@Slf4j
public class Library {
    public boolean someLibraryMethod() {
        log.debug("-----------------");
        return true;
    }
}
